# docker-compose.yml

version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/hydrogene

volumes:
  mongodb_data:
